create database customer_service;
use customer_service;
show tables;
select * from customer_table limit 20;
select distinct(gender)  from customer_table;


#Q1 what is the total revenue generated by male vs female customers
select gender ,sum(purchase_amount) from customer_table group by gender ;
select distinct(discount_applied) from customer_table;

## Q2 which customer used a discount but still spend more tham the average purchase amount?

select customer_id,purchase_amount from customer_table where discount_applied = "yes" and (select avg(purchase_amount) from customer_table) < purchase_amount;

##Q3.which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as avgg from customer_table group by item_purchased order by  avgg desc limit 5;
##Q4.compare the average purchase ammounts between standard and express shipping
select shipping_type , round(avg(purchase_amount),2) from customer_table  group by shipping_type having shipping_type in ("express","standard");
##Q5. do subscribed customers spend more? compare average spend and total revenued between subscribers and non subscribers? 
select subscription_status ,count(customer_id) as total_customers, avg(purchase_amount), sum(purchase_amount) from customer_table group by subscription_status ;


## Q6.which 5 product has the highest percentage of puchases with discounts applied  ---> it means i have to find which product relay heavily on discount to sell
## having is used for aggregate functions and group by 
select item_purchased, (sum(case when discount_applied= "yes" then 1 else 0 end)/count(customer_id))*100 as purchase_rate from customer_table group by item_purchased order by purchase_rate  desc limit 5;
 
 ##Q7.segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment.
 with previous_label as(
		select customer_id, previous_purchases,
        case
			when previous_purchases = 1 then "new"
            when previous_purchases between 2 and 10 then "returnning"
            else "loyal"
            end as purchase_group from customer_table 
      ) 
      select purchase_group,count(customer_id) as total_customer from previous_label group by purchase_group order by total_customer desc;
 
 ##Q8. what are the top 3 most purchased products within each category?
 with a as ( 
 select category, item_purchased,  count(customer_id) as cust_total,
			row_number() over(partition by category order by count(customer_id ) desc) as rn
            from customer_table group by category, item_purchased
            )
            select  * from a where rn <=3;
 
 
 
 ##Q9. are customers who are repeat buyers (more than 5 previous purchasses) also likely to subscribe?
 
 select subscription_status, count(customer_id) as total_cust from customer_table where previous_purchases > 5 group by subscription_status;
 select subscription_status, count(customer_id) as total_cust from customer_table where previous_purchases > 5 group by subscription_status;
## yhis will show how many repeat customer has subscribed and how many dont
 ### herre repeat means previous_purchases more than 5
 ##Q10. what is the revenue contribution of each age group;
select age_group  , sum(purchase_amount) as total_revenue from customer_table group by age_group order by  total_revenue desc;
## this is telling us which demographic is more relevant to the bussinesss